In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('/content/Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [6]:
df = df.drop(columns=['RowNumber','CustomerId','Surname'])

In [7]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [8]:
x = df.iloc[:,:-1].values

In [9]:
x.shape

(10000, 10)

In [10]:
df.shape

(10000, 11)

In [11]:
y = df.iloc[:,-1].values

In [12]:
y.shape

(10000,)

In [13]:
encoder = LabelEncoder()

x[:,1] = encoder.fit_transform(x[:,1])

In [14]:
x[:,2] = encoder.fit_transform(x[:,2])

In [15]:
transform = ColumnTransformer([("countries", OneHotEncoder(), [1])], remainder="passthrough") # 1 is the country column
x = transform.fit_transform(x)

In [16]:
print(x.shape)

x

(10000, 12)


array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [17]:
x = x[:,1:]
x.shape

(10000, 11)

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)

In [19]:
xd = pd.DataFrame(x)

xd.head()

0    1    2  3   4  5          6  7  8  9          10
0  0.0  0.0  619  0  42  2        0.0  1  1  1  101348.88
1  0.0  1.0  608  0  41  1   83807.86  1  0  1  112542.58
2  0.0  0.0  502  0  42  8   159660.8  3  1  0  113931.57
3  0.0  0.0  699  0  39  1        0.0  2  0  0   93826.63
4  0.0  1.0  850  0  43  2  125510.82  1  1  1    79084.1

In [20]:
sc = StandardScaler()

x_train[:,np.array([2,4,5,6,7,10])] = sc.fit_transform(x_train[:,np.array([2,4,5,6,7,10])])
x_test[:,np.array([2,4,5,6,7,10])] = sc.transform(x_test[:,np.array([2,4,5,6,7,10])])

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

x_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [21]:
from tensorflow.keras.models import Sequential

classifier = Sequential()

In [22]:
from tensorflow.keras.layers import Dense

classifier.add(Dense(activation='relu', input_dim=11, units = 256, kernel_initializer='uniform'))

In [23]:
classifier.add(Dense(activation='relu', units = 512, kernel_initializer='uniform'))

In [24]:
classifier.add(Dense(activation='relu', units = 256, kernel_initializer='uniform'))

In [25]:
classifier.add(Dense(activation = 'relu', units=128, kernel_initializer='uniform'))

In [26]:
classifier.add(Dense(activation = 'sigmoid', units=1, kernel_initializer='uniform'))

In [27]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])

In [28]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               3072      
                                                                 
 dense_1 (Dense)             (None, 512)               131584    
                                                                 
 dense_2 (Dense)             (None, 256)               131328    
                                                                 
 dense_3 (Dense)             (None, 128)               32896     
                                                                 
 dense_4 (Dense)             (None, 1)                 129       
                                                                 
Total params: 299,009
Trainable params: 299,009
Non-trainable params: 0
_________________________________________________________________


In [29]:
classifier.fit(
    x_train,y_train,
    validation_data = (x_test,y_test),
    epochs=20,
    batch_size=32
)

Epoch 1/20
250/250 [==============================] - 3s 8ms/step - loss: 0.4337 - accuracy: 0.8127 - val_loss: 0.3609 - val_accuracy: 0.8590
Epoch 2/20
250/250 [==============================] - 2s 7ms/step - loss: 0.3659 - accuracy: 0.8506 - val_loss: 0.3465 - val_accuracy: 0.8660
Epoch 3/20
250/250 [==============================] - 2s 7ms/step - loss: 0.3497 - accuracy: 0.8565 - val_loss: 0.3423 - val_accuracy: 0.8670
Epoch 4/20
250/250 [==============================] - 2s 7ms/step - loss: 0.3442 - accuracy: 0.8612 - val_loss: 0.3361 - val_accuracy: 0.8655
Epoch 5/20
250/250 [==============================] - 2s 7ms/step - loss: 0.3387 - accuracy: 0.8636 - val_loss: 0.3332 - val_accuracy: 0.8685
Epoch 6/20
250/250 [==============================] - 2s 7ms/step - loss: 0.3370 - accuracy: 0.8637 - val_loss: 0.3345 - val_accuracy: 0.8685
Epoch 7/20
250/250 [==============================] - 2s 7ms/step - loss: 0.3315 - accuracy: 0.8658 - val_loss: 0.3378 - val_accuracy: 0.8665
Epoch 

In [30]:
y_pred = classifier.predict(x_test)
y_pred

63/63 [==============================] - 0s 3ms/step


array([[0.35286924],
       [0.24642673],
       [0.1410825 ],
       ...,
       [0.00992319],
       [0.20224029],
       [0.2530168 ]], dtype=float32)

In [31]:
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [32]:
from sklearn.metrics import confusion_matrix,classification_report

cm1 = confusion_matrix(y_test, y_pred)
cm1

array([[1509,   86],
       [ 189,  216]])

In [33]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1595
           1       0.72      0.53      0.61       405

    accuracy                           0.86      2000
   macro avg       0.80      0.74      0.76      2000
weighted avg       0.85      0.86      0.85      2000



In [34]:
accuracy_model1 = ((cm1[0][0]+cm1[1][1])*100)/(cm1[0][0]+cm1[1][1]+cm1[0][1]+cm1[1][0])
print (accuracy_model1, '% of testing data was classified correctly')

86.25 % of testing data was classified correctly
